# Generated by Django 4.2.17 on 2025-05-22 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_renter', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Costume',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('extid', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/')),
                ('gender', models.CharField(choices=[('meski', 'Meski'), ('damski', 'Damski'), ('unisex', 'Unisex')], max_length=10)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=50)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('extid', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('meski', 'Meski'), ('damski', 'Damski')], max_length=10)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=50)),
                ('element_type', models.CharField(choices=[('nakrycie glowy', 'Nakrycie Glowy'), ('koszula', 'Koszula'), ('spodnie', 'Spodnie'), ('kamizelka', 'Kamizelka'), ('buty', 'Buty'), ('akcesoria', 'Akcesoria'), ('bizuteria', 'Bizuteria'), ('halka', 'Halka'), ('sukienka', 'Sukienka')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rented', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.BooleanField(default=False)),
                ('costume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.costume')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.element')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='costume',
            name='akcesoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='akcesoria', to='api.element'),
        ),
        migrations.AddField(
            model_name='costume',
            name='bizuteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bizuteria', to='api.element'),
        ),
        migrations.AddField(
            model_name='costume',
            name='buty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buty', to='api.element'),
        ),
        migrations.AddField(
            model_name='costume',
            name='halka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halka', to='api.element'),
        ),
        migrations.AddField(
            model_name='costume',
            name='kamizelka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kamizelka', to='api.element'),
        ),
        migrations.AddField(
            model_name='costume',
            name='koszula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='koszula', to='api.element'),
        ),
        migrations.AddField(
            model_name='costume',
            name='nakrycie_glowy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nakrycie_glowy', to='api.element'),
        ),
        migrations.AddField(
            model_name='costume',
            name='spodnie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spodnie', to='api.element'),
        ),
        migrations.AddField(
            model_name='costume',
            name='sukienka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sukienka', to='api.element'),
        ),
        migrations.AddField(
            model_name='costume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ControlMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
