# Generated by Django 4.2.17 on 2025-04-11 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElementStroju',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('extid', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('gender', models.CharField(choices=[('meski', 'Meski'), ('damski', 'Damski')], max_length=10)),
                ('element_type', models.CharField(choices=[('nakrycie glowy', 'Nakrycie Glowy'), ('koszula', 'Koszula'), ('spodnie', 'Spodnie'), ('kamizelka', 'Kamizelka'), ('buty', 'Buty'), ('akcesoria', 'Akcesoria'), ('bizuteria', 'Bizuteria'), ('halka', 'Halka'), ('sukienka', 'Sukienka')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stroj',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('extid', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('gender', models.CharField(choices=[('meski', 'Meski'), ('damski', 'Damski')], max_length=10)),
                ('akcesoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='akcesoria', to='api.elementstroju')),
                ('bizuteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bizuteria', to='api.elementstroju')),
                ('buty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buty', to='api.elementstroju')),
                ('halka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halka', to='api.elementstroju')),
                ('kamizelka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kamizelka', to='api.elementstroju')),
                ('koszula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='koszula', to='api.elementstroju')),
                ('nakrycie_glowy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nakrycie_glowy', to='api.elementstroju')),
                ('spodnie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spodnie', to='api.elementstroju')),
                ('sukienka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sukienka', to='api.elementstroju')),
            ],
        ),
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wypozyczono', models.DateTimeField(auto_now_add=True)),
                ('zwrot', models.DateTimeField(blank=True, null=True)),
                ('rezerwacja', models.BooleanField(default=False)),
                ('element_stroju', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.elementstroju')),
                ('stroj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.stroj')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
