# Generated by Django 4.2.17 on 2024-12-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementStroju',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('gender', models.CharField(choices=[('meski', 'Meski'), ('damski', 'Damski')], max_length=10)),
                ('element_type', models.CharField(choices=[('nakrycie glowy', 'Nakrycie Glowy'), ('koszula', 'Koszula'), ('spodnie', 'Spodnie'), ('kamizelka', 'Kamizelka'), ('buty', 'Buty'), ('akcesoria', 'Akcesoria'), ('bizuteria', 'Bizuteria'), ('halka', 'Halka'), ('sukienka', 'Sukienka')], max_length=50)),
            ],
        ),
    ]
