# Generated by Django 4.2.17 on 2025-05-24 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rental_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costume',
            name='akcesoria',
        ),
        migrations.RemoveField(
            model_name='costume',
            name='bizuteria',
        ),
        migrations.RemoveField(
            model_name='costume',
            name='buty',
        ),
        migrations.RemoveField(
            model_name='costume',
            name='halka',
        ),
        migrations.RemoveField(
            model_name='costume',
            name='kamizelka',
        ),
        migrations.RemoveField(
            model_name='costume',
            name='koszula',
        ),
        migrations.RemoveField(
            model_name='costume',
            name='nakrycie_glowy',
        ),
        migrations.RemoveField(
            model_name='costume',
            name='spodnie',
        ),
        migrations.RemoveField(
            model_name='costume',
            name='sukienka',
        ),
        migrations.AddField(
            model_name='costume',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='api.element'),
        ),
        migrations.AddField(
            model_name='costume',
            name='dress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dress', to='api.element'),
        ),
        migrations.AddField(
            model_name='costume',
            name='headwear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headwear', to='api.element'),
        ),
        migrations.AddField(
            model_name='costume',
            name='jewelry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jewelry', to='api.element'),
        ),
        migrations.AddField(
            model_name='costume',
            name='petticoat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petticoat', to='api.element'),
        ),
        migrations.AddField(
            model_name='costume',
            name='shirt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirt', to='api.element'),
        ),
        migrations.AddField(
            model_name='costume',
            name='shoes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='api.element'),
        ),
        migrations.AddField(
            model_name='costume',
            name='trousers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trousers', to='api.element'),
        ),
        migrations.AddField(
            model_name='costume',
            name='vest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vest', to='api.element'),
        ),
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.CharField(choices=[('headwear', 'Headwear'), ('shirt', 'Shirt'), ('trousers', 'Trousers'), ('vest', 'Vest'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('jewelry', 'Jewelry'), ('petticoat', 'Petticoat'), ('dress', 'Dress')], max_length=50),
        ),
    ]
