# Generated by Django 4.2.17 on 2025-04-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stroj_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementstroju',
            name='element_type',
            field=models.CharField(choices=[('nakrycie głowy', 'Nakrycie Głowy'), ('koszula', 'Koszula'), ('spodnie', 'Spodnie'), ('kamizelka', 'Kamizelka'), ('buty', 'Buty'), ('akcesoria', 'Akcesoria'), ('bizuteria', 'Bizuteria'), ('halka', 'Halka'), ('sukienka', 'Sukienka')], max_length=50),
        ),
    ]
