# Generated by Django 4.2.17 on 2024-12-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_elementstroju'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementstroju',
            name='extid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
