# Generated by Django 4.2.17 on 2025-04-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_elementstroju_element_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementstroju',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
        migrations.AddField(
            model_name='stroj',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
    ]
