# Generated by Django 4.2.17 on 2025-05-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_costume_akcesoria_remove_costume_bizuteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costume',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], max_length=10),
        ),
        migrations.AlterField(
            model_name='element',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
