# Generated by Django 4.2.17 on 2024-12-29 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_elementstroju_extid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementstroju',
            name='extid',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Stroj',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('extid', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('gender', models.CharField(choices=[('meski', 'Meski'), ('damski', 'Damski')], max_length=10)),
                ('akcesoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='akcesoria', to='api.elementstroju')),
                ('bizuteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bizuteria', to='api.elementstroju')),
                ('buty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buty', to='api.elementstroju')),
                ('halka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halka', to='api.elementstroju')),
                ('kamizelka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kamizelka', to='api.elementstroju')),
                ('koszula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='koszula', to='api.elementstroju')),
                ('nakrycie_glowy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nakrycie_glowy', to='api.elementstroju')),
                ('spodnie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spodnie', to='api.elementstroju')),
                ('sukienka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sukienka', to='api.elementstroju')),
            ],
        ),
    ]
