# Generated by Django 4.2.17 on 2025-01-26 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_elementstroju_extid_stroj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wypozyczono', models.DateTimeField(auto_now_add=True)),
                ('zwrot', models.DateTimeField(blank=True, null=True)),
                ('element_stroju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.elementstroju')),
                ('stroj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stroj')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
