# Generated by Django 4.2.17 on 2025-04-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_elementstroju_image_stroj_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementstroju',
            name='city',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
