# Generated by Django 4.2.17 on 2025-01-26 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_wypozyczenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wypozyczenie',
            name='element_stroju',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.elementstroju'),
        ),
        migrations.AlterField(
            model_name='wypozyczenie',
            name='stroj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.stroj'),
        ),
    ]
