# Generated by Django 4.2.17 on 2025-04-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_elementstroju_user_stroj_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_renter',
            field=models.BooleanField(default=False),
        ),
    ]
