# Generated by Django 4.2.17 on 2025-05-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wypozyczenie',
            name='wypozyczono',
            field=models.DateTimeField(),
        ),
    ]
