# Generated by Django 4.2.17 on 2025-05-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_wiadomoscikontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementstroju',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stroj',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
