# Generated by Django 4.2.17 on 2025-05-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_elementstroju_confirmed_stroj_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementstroju',
            name='element_type',
            field=models.CharField(choices=[('nakrycie glowy', 'Nakrycie Glowy'), ('koszula', 'Koszula'), ('spodnie', 'Spodnie'), ('kamizelka', 'Kamizelka'), ('buty', 'Buty'), ('akcesoria', 'Akcesoria'), ('bizuteria', 'Bizuteria'), ('halka', 'Halka'), ('sukienka', 'Sukienka')], max_length=50),
        ),
    ]
